import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TaxProvider } from '../contexts/TaxContext';
import { SeriesProvider } from '../contexts/SeriesContext';
import { CompanyProvider } from '../contexts/CompanyContext';
import { NotificationProvider } from '../contexts/NotificationContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TaxProvider>
          <SeriesProvider>
            <CompanyProvider>
              <NotificationProvider>
                {children}
              </NotificationProvider>
            </CompanyProvider>
          </SeriesProvider>
        </TaxProvider>
      </body>
    </html>
  );
}
